# Generated by Django 2.0.4 on 2018-05-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='publisher',
            field=models.CharField(default='', max_length=200),
        ),
    ]
